### ISSUE TITLE
MacOS testers needed

### ISSUE THREAD

**Issue by ngirard** [ngirard/lolcate-rs#21]
I believe Lolcate should work gracefully on MacOS, but didn't have a chance to check it.
Pre-built binaries are provided for MacOS with each release.
It would be nice if someone could test them.

**Comment by lws4701** [comment]
Is there any functionality in particular you want tested? I actually just did a cargo build, and so far, just testing it out, it seems to work great.

**Comment by ngirard** [comment]
Hey @lwsmith98, thanks for proposing !
I guess we should be good after the following:
* could you please try the pre-compiled binary ?
* could you create a second database and see if you can update and query it ?
* just out of curiosity, what does `lolcate --info` return ?

**Comment by lws4701** [comment]
Adding a second database and updating it works successfully. Now, I haven't looked over the codebase very closely yet, but just curious, where are these dbs being stored in the fs?
Attached below is the result of ./lolcate --info
<img width="559" alt="Screen Shot 2020-05-21 at 5 33 02 PM" src="https://user-images.githubusercontent.com/45962128/82613106-21052980-9b8a-11ea-8f21-278f31525460.png">

**Comment by lws4701** [comment]
Nix that one question, I found it after reading the data_dirs documentation.

**Comment by segunolulana** [comment]
I just tried using the prebuilt binary on High Sierra i.e Mac 10.13.6 and it failed immediately with several os errors  and errors about Mac version 
```
failed to access entry (/Users/myuser/Library/Application Support/Joplin/SingletonLock: No such file or directory (os error 2))
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/myuser/bin/lolcate (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/myuser/bin/lolcate (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    21367 abort      sudo lolcate --update

**Comment by ngirard** [comment]
Sorry for the late reply.
@lwsmith98, thanks for your previous feedback !
@segunolulana, would you mind trying the latest release ?

**Comment by segunolulana** [comment]
The latest prebuilt binary still fails on High Sierra (Mac 10.13.6). It however works well on Catalina (Mac 10.15.3). From the error message, it seems it might only work for Mac 10.15
```
➜  ~ lolcate --update --db user
Updating user...
failed to access entry (/Users/segun/Library/Saved Application State/com.aone.keka.savedState: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Saved Application State/com.apple.Notes.savedState: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Saved Application State/com.automattic.SimplenoteMac.savedState: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Slimjet/App Shim Socket: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Cerebro/SS: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Cerebro/SingletonCookie: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Cerebro/SingletonLock: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/com.operasoftware.Opera/SingletonCookie: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/com.operasoftware.Opera/SingletonLock: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Slack/SingletonCookie: No such file or directory (os error 2))
failed to access entry (/Users/segun/Library/Application Support/Slack/SingletonLock: No such file or directory (os error 2))
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/segun/bin/lolcate (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/segun/bin/lolcate (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

[1]    16458 abort      lolcate --update --db user
➜  ~ lolcate --db user info
```

**Comment by ngirard** [comment]
@segunolulana, thanks for reporting.
Yes, the binary for MacOS is built against the latest MacOS release. Is it acceptable for you, or should I try & come up with another bonary for earlier releases ?
BTW, are you using Lolcate ?

**Comment by segunolulana** [comment]
Okay. That is fine. It might be better to state the minimum MacOS version though to prevent surprises for new users. I'm not actively using it but I just tried testing it and it works well on Mac 10.15
